# Generated by Django 6.0.7 on 2026-07-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_location', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='InstitutionContact',
            fields=[
                ('institution_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_contact_number', models.CharField(max_length=50)),
                ('institution_contact_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Landline', 'Landline'), ('Email', 'Email')], max_length=50)),
                ('institution_contact_last_update', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.institution')),
            ],
            options={
                'db_table': 'institution_contact',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professional_id', models.AutoField(primary_key=True, serialize=False)),
                ('professional_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('professional_name', models.CharField(max_length=255)),
                ('professional_specialization', models.CharField(choices=[('Psychiatry', 'Psychiatry'), ('Psychology', 'Psychology')], max_length=50)),
                ('professional_last_updated', models.DateTimeField()),
                ('professional_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.institution')),
            ],
            options={
                'db_table': 'professional',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('affiliation_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.institution')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.professional')),
            ],
            options={
                'db_table': 'affiliation',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=50)),
                ('contact_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Landline', 'Landline'), ('Email', 'Email')], max_length=50)),
                ('contact_last_updated', models.DateTimeField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.professional')),
            ],
            options={
                'db_table': 'professional_contact',
            },
        ),
        migrations.CreateModel(
            name='SessionReferral',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='callers.callsession')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.affiliation')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.professional')),
            ],
            options={
                'db_table': 'session_referral',
            },
        ),
    ]
