# Generated by Django 6.0.7 on 2026-07-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('caller_id', models.AutoField(primary_key=True, serialize=False)),
                ('caller_name', models.CharField(default='Anonymous', max_length=255)),
                ('caller_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('caller_civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('caller_number', models.IntegerField(blank=True, null=True)),
                ('caller_age', models.IntegerField(blank=True, null=True)),
                ('caller_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'caller',
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('session_call_date', models.DateField()),
                ('session_time_called', models.TimeField()),
                ('session_time_ended', models.TimeField(blank=True, null=True)),
                ('session_reason_for_calling', models.CharField(blank=True, max_length=255, null=True)),
                ('session_risk_assessment', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('session_intervention', models.TextField(blank=True, null=True)),
                ('session_additional_comments', models.TextField(blank=True, null=True)),
                ('session_summarization', models.TextField()),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callers.caller')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shiftcatalog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'call_session',
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='callers.callsession')),
            ],
            options={
                'db_table': 'call_transcript',
            },
        ),
    ]
