# Generated by Django 6.0.7 on 2026-07-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('user_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('Responder', 'Responder')], max_length=50)),
                ('user_location', models.CharField(blank=True, max_length=255, null=True)),
                ('user_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='DayOffRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_date', models.DateField()),
                ('requested_reason', models.CharField(max_length=255)),
                ('requested_additional_notes', models.TextField(blank=True, null=True)),
                ('requested_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=50)),
                ('processed_by', models.ForeignKey(blank=True, db_column='processed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayoffrequest_processed_by_set', to='accounts.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayoffrequest_user_set', to='accounts.user')),
            ],
            options={
                'db_table': 'day_off_request',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_token', models.CharField(max_length=255)),
                ('log_time_in', models.DateTimeField(auto_now_add=True)),
                ('log_time_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
    ]
