# Generated by Django 6.0.7 on 2026-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_image_alter_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
