# Generated by Django 6.0.7 on 2026-07-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_setup_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
