# Generated by Django 6.0.7 on 2026-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_setup_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoffrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
