# Generated by Django 6.0.7 on 2026-07-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=255)),
                ('report_generated_date', models.DateField()),
                ('report_type', models.CharField(choices=[('Compliance', 'Compliance'), ('Analytics', 'Analytics'), ('Security', 'Security')], max_length=100)),
                ('generated_by', models.ForeignKey(db_column='generated_by', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
