# Generated by Django 6.0.7 on 2026-07-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCatalog',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], max_length=50)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
            ],
            options={
                'db_table': 'shift_catalog',
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('schedule_status', models.CharField(max_length=50)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shiftcatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'shift_schedule',
            },
        ),
    ]
