# Generated by Django 6.0.7 on 2026-08-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftcatalog',
            name='shift_name',
        ),
    ]
