# Generated by Django 6.0.7 on 2026-08-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_shiftcatalog_shift_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
