# Generated by Django 6.0.7 on 2026-08-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_shiftschedule_shift_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftschedule',
            name='shift_date',
        ),
    ]
