# Generated by Django 6.0.7 on 2026-08-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_shiftschedule_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='days_off',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
