# Generated by Django 6.0.7 on 2026-08-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_shiftschedule_days_off'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftschedule',
            old_name='shift_end_date',
            new_name='shift_date',
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='days_off',
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='shift_start_date',
        ),
    ]
